(in-package :vpw2012)

(defun file-lines (filename)
  (iter (for line in-file filename using #'read-line)
	(collect (remove #\Return line))))

(defparameter *problem-directory* #P"c:/users/serge.demarre/appdata/roaming/src/lisp/systems/vpw2012/data/")

(defun example-input-lines (problemname)
  (file-lines (merge-pathnames *problem-directory* (format nil "~a-voorbeeld.input.txt" problemname))))
(defun example-output-lines (problemname)
  (file-lines (merge-pathnames *problem-directory* (format nil "~a-voorbeeld.output.txt" problemname))))
(defun problem-input-lines (problemname)
  (file-lines (merge-pathnames *problem-directory* (format nil "~a-wedstrijd.input.txt" problemname))))
(defun problem-output-lines (problemname)
  (file-lines (merge-pathnames *problem-directory* (format nil "~a-wedstrijd.output.txt" problemname))))

(defun make-line-producer (lines)
  (let ((lines lines))
    #'(lambda () (prog1
		     (first lines)
		   (setf lines (rest lines))))))

(defun problem-names ()
  (list "dominos" "hercules" "morse" "veelhoeken" "woordsnippers"))

(defmacro with-some-entries ((problem-name line-producer line-fetcher-func) &body body)
  (let ((problem-lines (gensym))
	(number-problems (gensym)))
    `(let* ((,problem-lines (,line-fetcher-func ,problem-name))
	    (,line-producer (make-line-producer ,problem-lines))
	    (,number-problems (parse-integer (funcall ,line-producer))))
       (iter (for problem from 1 to ,number-problems)
	     ,@body))))
(defmacro with-problem-entries ((problem-name line-producer) &body body)
  `(with-some-entries (,problem-name ,line-producer problem-input-lines)
     ,@body))
(defmacro with-example-entries ((problem-name line-producer) &body body)
  `(with-some-entries (,problem-name ,line-producer example-input-lines)
     ,@body))
